name: Hello World

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
          java-version: "19"
          distribution: "temurin"


      - name: Install dep and run tests
        run: mvn test
